package com.pd.palette.compose.colors

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class SportsNetworkColors(
    val isLight: Boolean,
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundTertiary: Color,
    val backgroundQuaternary: Color,
    val backgroundQuinary: Color,
    val backgroundSenary: Color,
    val backgroundSeptenary: Color,
    val backgroundOctonary: Color,
    val backgroundSecondaryContrary: Color,
    val backgroundPremium: Color,
    val backgroundLightAccent: Color,
    val borderPrimary: Color,
    val borderSecondary: Color,
    val borderTertiary: Color,
    val borderQuaternary: Color,
    val borderQuinary: Color,
    val accentPrimary: Color,
    val accentSecondary: Color,
    val accentTertiary: Color,
    val accentQuaternary: Color,
    val accentQuinary: Color,
    val alertPrimary: Color,
    val alertSecondary: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textQuaternary: Color,
    val textQuinary: Color,
    val textSecondaryContrary: Color,
    val textOnAccentPrimary: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val iconTertiary: Color,
    val iconQuaternary: Color,
    val iconSecondaryContrary: Color,
    val iconDisabled: Color,
    val iconDisabled50: Color,
    val iconQuinary: Color,
    val blueBayoux: Color,
    val bismark: Color,
    val tangerineYellow: Color,
    val buttonTextPrimary: Color,
    val backgroundScrim: Color,
    val squash: Color,
    val marigoldYellow: Color,
    val gradientPrimary: Color,
    val gradientSecondary: Color,
    val gradientTertiary: Color,
    val gradientQuaternary: Color,

)